import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Jillian and Braedens Wedding",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <audio
        id="bg-music"
        src="/audio/piano-moment-9835.mp3"
        loop
        preload="auto"
      />
      {children}
    </>
  );
}
