import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

export const metadata = {
  title: "Jillian and Braedens Wedding",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <audio
        id="bg-music"
        src="/audio/piano-moment-9835.mp3"
        loop
        preload="auto"
      />
      {children}
    </>
  );
}
